### ISSUE TITLE
[pip package] model directory is missing

### ISSUE THREAD

**Issue by kalidor** [breitburg/python-lametric#3]
Hi, thanks for this project, I'm just testing it by installing it using pip: `pip install lametric`.

Version installed: `lametric-2.0.0.dist-info`

Unfortunately, it seems the `model` directory is missing:
```python
>>> from lametric.discovery import discover
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gch/.local/lib/python3.8/site-packages/lametric/discovery.py", line 3, in <module>
    from lametric.device import Time as _Time
  File "/home/gch/.local/lib/python3.8/site-packages/lametric/device.py", line 6, in <module>
    from lametric.model.sound import Sound as _Sound
ModuleNotFoundError: No module named 'lametric.model'
```

And obviously in site-packages directory, we can see it's missing:
```bash
<prompt>% ls -l ~/.local/lib/python3.8/site-packages/lametric 
Permissions Size User Group Date Modified  Name
drwxrwxr-x     - gch  gch   21 mars  19:25 __pycache__
.rw-rw-r--     0 gch  gch   21 mars  19:25 __init__.py
.rw-rw-r--  4,3k gch  gch   21 mars  19:25 device.py
.rw-rw-r--   376 gch  gch   21 mars  19:25 discovery.py
<prompt>% 
```

We can also confirm that by unzipping the .egg file created during build process (even by installing the package by hand using git)

**Comment by breitburg** [comment]
Thank you for contributing! I have merged your pull request.
